// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce_flutter/hive_ce_flutter.dart';
import 'package:news_app/core/models/user_model.dart';
import 'package:news_app/feathures/bookmark/model/bookmark_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BookmarkModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BookmarkModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
